Specify the MIME type of images when uploading them
It turns out that PopIt will return the images as
application/octet-stream unless you manually specify their MIME type.

diff --git a/bin/upload-photo b/bin/upload-photo
--- a/bin/upload-photo
+++ b/bin/upload-photo
@@ -47,11 +47,30 @@ then
     exit 1
 fi
 
+EXTENSION="$(echo ${FILENAME##*.} | tr '[A-Z]' '[a-z]')"
+
+case $EXTENSION in
+    png)
+        MIME_TYPE='image/png'
+        ;;
+    jpg|jpeg)
+        MIME_TYPE='image/jpeg'
+        ;;
+    gif)
+        MIME_TYPE='image/gif'
+        ;;
+    *)
+        echo "Couldn't infer the file type from filename $FILENAME"
+        exit 1
+        ;;
+esac
+
 if ! curl -f \
     --request POST \
     --header "APIKey: $APIKEY" \
     -F notes="Manually uploaded from the command line" \
     -F image="@$FILENAME" \
+    -F mime_type="$MIME_TYPE" \
     "$PERSON_API_URL/image" > /dev/null
 then
     echo "Uploading the photo failed"
